# Generated by Django 3.0.6 on 2020-05-08 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=100, verbose_name='name')),
                ('details', models.TextField(default='NA', verbose_name='details')),
            ],
        ),
        migrations.CreateModel(
            name='Released',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_block_hash', models.TextField(default='NA', verbose_name='previous')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 19, 42, 13, 75419), verbose_name='timestamp')),
                ('current_hash', models.TextField(default='NA', verbose_name='current')),
                ('name', models.CharField(default='NA', max_length=100, verbose_name='name')),
                ('address', models.TextField(default='NA', max_length=500, verbose_name='address')),
                ('contact', models.CharField(default='NA', max_length=20, verbose_name='contact')),
                ('bed', models.IntegerField(default=0, verbose_name='bed')),
                ('doctor', models.TextField(default='NA', verbose_name='doctor')),
                ('emergency', models.CharField(default='n', max_length=3, verbose_name='emergency')),
                ('deceased', models.CharField(default='n', max_length=3, verbose_name='deceased')),
                ('billings', models.TextField(default='NA', max_length=500, verbose_name='billings')),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=100, verbose_name='name')),
                ('address', models.TextField(default='NA', max_length=500, verbose_name='address')),
                ('contact', models.CharField(default='NA', max_length=20, verbose_name='contact')),
                ('bed', models.IntegerField(default=0, verbose_name='bed')),
                ('emergency', models.CharField(default='n', max_length=3, verbose_name='emergency')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=100, verbose_name='name')),
                ('address', models.TextField(default='NA', max_length=500, verbose_name='address')),
                ('details', models.TextField(default='NA', verbose_name='details')),
                ('amount', models.IntegerField(default=0, verbose_name='amount')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Patient')),
            ],
        ),
    ]
