# Generated by Django 3.0.6 on 2020-05-08 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='released',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 21, 8, 47, 248019), verbose_name='timestamp'),
        ),
    ]
